# Generated by Django 2.2.3 on 2019-07-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190718_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='local',
            field=models.CharField(default=1, max_length=100, verbose_name='Local'),
            preserve_default=False,
        ),
    ]
